apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: search-service
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2113
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: api-config
