apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: search-service
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: search:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
              name: grpc
            - containerPort: 2114
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: search-config
          livenessProbe:
            grpc:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
