// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks.go -package=core
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetAllComicsInfo mocks base method.
func (m *MockDB) GetAllComicsInfo(ctx context.Context) ([]ComicInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllComicsInfo", ctx)
	ret0, _ := ret[0].([]ComicInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllComicsInfo indicates an expected call of GetAllComicsInfo.
func (mr *MockDBMockRecorder) GetAllComicsInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllComicsInfo", reflect.TypeOf((*MockDB)(nil).GetAllComicsInfo), ctx)
}

// GetComicsByIds mocks base method.
func (m *MockDB) GetComicsByIds(ctx context.Context, ids []int64) ([]Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicsByIds", ctx, ids)
	ret0, _ := ret[0].([]Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicsByIds indicates an expected call of GetComicsByIds.
func (mr *MockDBMockRecorder) GetComicsByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicsByIds", reflect.TypeOf((*MockDB)(nil).GetComicsByIds), ctx, ids)
}

// MockWords is a mock of Words interface.
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *MockWordsMockRecorder
	isgomock struct{}
}

// MockWordsMockRecorder is the mock recorder for MockWords.
type MockWordsMockRecorder struct {
	mock *MockWords
}

// NewMockWords creates a new mock instance.
func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &MockWordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWords) EXPECT() *MockWordsMockRecorder {
	return m.recorder
}

// Norm mocks base method.
func (m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Norm", ctx, phrase)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Norm indicates an expected call of Norm.
func (mr *MockWordsMockRecorder) Norm(ctx, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Norm", reflect.TypeOf((*MockWords)(nil).Norm), ctx, phrase)
}

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// ISearch mocks base method.
func (m *MockSearcher) ISearch(ctx context.Context, phrase string, limit int64) ([]Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISearch", ctx, phrase, limit)
	ret0, _ := ret[0].([]Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISearch indicates an expected call of ISearch.
func (mr *MockSearcherMockRecorder) ISearch(ctx, phrase, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISearch", reflect.TypeOf((*MockSearcher)(nil).ISearch), ctx, phrase, limit)
}

// ResetIndex mocks base method.
func (m *MockSearcher) ResetIndex() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetIndex")
}

// ResetIndex indicates an expected call of ResetIndex.
func (mr *MockSearcherMockRecorder) ResetIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetIndex", reflect.TypeOf((*MockSearcher)(nil).ResetIndex))
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, phrase string, limit int64) ([]Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, phrase, limit)
	ret0, _ := ret[0].([]Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, phrase, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, phrase, limit)
}

// UpdateIndex mocks base method.
func (m *MockSearcher) UpdateIndex(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndex", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndex indicates an expected call of UpdateIndex.
func (mr *MockSearcherMockRecorder) UpdateIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndex", reflect.TypeOf((*MockSearcher)(nil).UpdateIndex), ctx)
}

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// HandleEvent mocks base method.
func (m *MockEventHandler) HandleEvent(ctx context.Context, eventType EventType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEvent", ctx, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockEventHandlerMockRecorder) HandleEvent(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockEventHandler)(nil).HandleEvent), ctx, eventType)
}
