apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: search-service
spec:
  type: ClusterIP
  selector:
    app: search
  ports:
    - name: grpc
      port: 8083
      targetPort: 8083
    - name: metrics
      port: 2114
      targetPort: 2114
