apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: search-service
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "frontend"
        static_configs:
          - targets: ["frontend:2112"]
        scrape_interval: 10s

      - job_name: "api"
        static_configs:
          - targets: ["api:2113"]
        scrape_interval: 10s

      - job_name: "search"
        static_configs:
          - targets: ["search:2114"]
        scrape_interval: 10s

      - job_name: "update"
        static_configs:
          - targets: ["update:2115"]
        scrape_interval: 10s
